<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="date" content="2017-12-18" />

<title>Boston Housing Dataset</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #ffffff; color: #1f1c1b; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; background-color: #ffffff; color: #a0a0a0; border-right: 1px solid #a0a0a0; }
td.sourceCode { padding-left: 5px; }
pre, code { color: #1f1c1b; background-color: #ffffff; }
code > span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code > span.dt { color: #0057ae; } /* DataType */
code > span.dv { color: #b08000; } /* DecVal */
code > span.bn { color: #b08000; } /* BaseN */
code > span.fl { color: #b08000; } /* Float */
code > span.cn { color: #aa5500; } /* Constant */
code > span.ch { color: #924c9d; } /* Char */
code > span.sc { color: #3daee9; } /* SpecialChar */
code > span.st { color: #bf0303; } /* String */
code > span.vs { color: #bf0303; } /* VerbatimString */
code > span.ss { color: #ff5500; } /* SpecialString */
code > span.im { color: #ff5500; } /* Import */
code > span.co { color: #898887; } /* Comment */
code > span.do { color: #607880; } /* Documentation */
code > span.an { color: #ca60ca; } /* Annotation */
code > span.cv { color: #0095ff; } /* CommentVar */
code > span.ot { color: #006e28; } /* Other */
code > span.fu { color: #644a9b; } /* Function */
code > span.va { color: #0057ae; } /* Variable */
code > span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code > span.op { color: #1f1c1b; } /* Operator */
code > span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code > span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code > span.pp { color: #006e28; } /* Preprocessor */
code > span.at { color: #0057ae; } /* Attribute */
code > span.re { color: #0057ae; } /* RegionMarker */
code > span.in { color: #b08000; } /* Information */
code > span.wa { color: #bf0303; } /* Warning */
code > span.al { color: #bf0303; font-weight: bold; } /* Alert */
code > span.er { color: #bf0303; text-decoration: underline; } /* Error */
code > span. { color: #1f1c1b; } /* Normal */
div.sourceCode {
  overflow-x: visible;
}
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 45px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 50px;
  margin-top: -50px;
}

.section h2 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h3 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h4 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h5 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h6 {
  padding-top: 50px;
  margin-top: -50px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">IODS Final Project</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    IODS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://wiki.helsinki.fi/display/SocStats/Introduction+to+Open+Data+Science%2C+spring+2017">Course Information</a>
    </li>
    <li>
      <a href="https://kisun.github.io/IODS-project/">My Learning Diary</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About me</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Boston Housing Dataset</h1>
<h4 class="author"><em>Kisun Pokharel</em></h4>
<address class="author_afil">
Natural Resources Institute Finland (Luke)<br><a class="author_email" href="mailto:#"><a href="mailto:kisun.pokharel@helsinki.fi">kisun.pokharel@helsinki.fi</a></a>
</address>
<h4 class="date"><em>December 18, 2017</em></h4>

</div>


<div id="abstract" class="section level1">
<h1>Abstract</h1>
<p>This report is the final assignment of the <a href="https://wiki.helsinki.fi/display/SocStats/Introduction+to+Open+Data+Science%2C+spring+2017">IODS course</a>. The Boston dataset available from MASS package was used to perform multiple linear regression analysis . The analysis showed that the housing price in Boston may determine if the owner could have crime history. In other words, the price of owner occupied homes proved to be highly significant in determining the crime rate.</p>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>The Boston Housing Dataset contains information related to housing in the area of Boston Mass.</p>
</div>
<div id="data-wrangling" class="section level1">
<h1>Data Wrangling</h1>
<p>Before proceeding with the statistical analyses, we will first go through some data wrangling steps. In many cases, the available (raw) data may contain noise such as missing values and are usually untidy and poorly formatted. Therefore, the aim of data wrangling step is to convert raw data into clean (analysis ready) data and to make sure that the dataset satisfies the following conditions:</p>
<ol style="list-style-type: decimal">
<li>all observations are stored in rows</li>
<li>all variables are in columns</li>
<li>all data under study are kept in single dataset</li>
</ol>
<p>The R script for data wrangling can be found with <a href="https://github.com/kisun/IODS-final/blob/master/data/create_boston.R">this link</a>.</p>
</div>
<div id="data-summary" class="section level1">
<h1>Data Summary</h1>
<p>The <strong>Boston</strong> data was collected to study the housing values in the suburbs of Boston. The table contains 506 observations for 14 different variables. The descriptions for each of the 14 variables are listed below.</p>
<table style="width:100%;">
<colgroup>
<col width="13%" />
<col width="86%" />
</colgroup>
<thead>
<tr class="header">
<th>Variables</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>crim</td>
<td>per capita crime rate by town.</td>
</tr>
<tr class="even">
<td>zn</td>
<td>proportion of residential land zoned for lots over 25,000 sq.ft.</td>
</tr>
<tr class="odd">
<td>indus</td>
<td>proportion of non-retail business acres per town.</td>
</tr>
<tr class="even">
<td>chas</td>
<td>Charles River dummy variable (= 1 if tract bounds river; 0 otherwise).</td>
</tr>
<tr class="odd">
<td>nox</td>
<td>nitrogen oxides concentration (parts per 10 million).</td>
</tr>
<tr class="even">
<td>rm</td>
<td>average number of rooms per dwelling.</td>
</tr>
<tr class="odd">
<td>age</td>
<td>proportion of owner-occupied units built prior to 1940.</td>
</tr>
<tr class="even">
<td>dis</td>
<td>weighted mean of distances to five Boston employment centres.</td>
</tr>
<tr class="odd">
<td>rad</td>
<td>index of accessibility to radial highways.</td>
</tr>
<tr class="even">
<td>tax</td>
<td>full-value property-tax rate per $10,000.</td>
</tr>
<tr class="odd">
<td>ptratio</td>
<td>pupil-teacher ratio by town.</td>
</tr>
<tr class="even">
<td>black</td>
<td>1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town.</td>
</tr>
<tr class="odd">
<td>lstat</td>
<td>lower status of the population (percent).</td>
</tr>
<tr class="even">
<td>medv</td>
<td>median value of owner-occupied homes in $1000s.</td>
</tr>
</tbody>
</table>
<p>First and foremost, it is important to get an overview of the data being analysed. As mentioned earlier, Boston data is available from <a href="https://cran.r-project.org/web/packages/MASS/index.html">MASS package</a> and thus can be directly imported into R for further analysis.</p>
</div>
<div id="data-exploration" class="section level1">
<h1>Data Exploration</h1>
<div id="preliminary-hypotheses" class="section level2">
<h2>Preliminary hypotheses</h2>
<p>Just by looking at the varibles above, one can make few assumptions regarding the inter-relationships between different variables. Let’s start with some assumptions:</p>
<p>Here, the main goal of the analysis is to study how crime rate is associated with other aspects in Boston. After going through the background information, it is a bit easier to identify interesting variables that could be related to criminal activities. Personally, I believe that the following are the four interesting variables that are associated with crime rates:</p>
<p><strong>1. Accessibility to radial highways (rad)</strong> : In my opinion, accessibility to radial highways plays vital role when it comes to crime related activities. Criminals may prefer towns with rapid access to radial highways especially for escaping purpose. Therefore, I believe that accessibility to radial highways may contribute to higher crime rates.</p>
<p><strong>2. Value of owner-occupied homes (medv)</strong> : Usually, the crime-related activities are common with individuals who do not have enough property. They say that one of the main reasons for crime is poverty. Individual with basic income may also have homes with lower value but I think we can also correlate the value of house one has with crime-rate. In other words, value of owner-occupied home should be negatively correlated with crime.</p>
<p><strong>3. Distance to employment centers in Boston (dis)</strong> : I hypothesize that the farther the residential area from employment centers, the higher the crime rates.</p>
<p><strong>4. Proportion of blacks(black)</strong> : There have been an impression that blacks commit more crime compared to whites. Therefore, I hypothesize that proportion of blacks is positively correlated with crime rate.</p>
<p>In the following section, we will see in details how my hypotheses are explained by the data.</p>
</div>
<div id="non-graphical-data-exploration" class="section level2">
<h2>Non-graphical data exploration</h2>
<p>Non-graphical data exploration is the first step before we start analyzing the data. This step different aspects of the data here we will cover three of those:</p>
<ol style="list-style-type: decimal">
<li>measures of central tendency (mean, meadian)</li>
<li>measures of variability (interquartile range, standard deviation)</li>
<li>relationships between variables (correlation)</li>
</ol>
<p>Now, let’s first look at the summary of the boston data in the form of table (instead of default layout) using <em>pandoc.table</em> function of <strong>pander</strong> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pandoc.table</span>(<span class="kw">summary</span>(Boston), <span class="dt">caption =</span> <span class="st">&quot;Summary of Boston data&quot;</span>, <span class="dt">split.table =</span> <span class="dv">100</span>)</code></pre></div>
<pre><code>## 
## --------------------------------------------------------------------------------------
##        crim               zn             indus            chas              nox       
## ------------------ ---------------- --------------- ----------------- ----------------
##  Min.  : 0.00632     Min.  : 0.00    Min.  : 0.46    Min.  :0.00000    Min.  :0.3850  
## 
##  1st Qu.: 0.08204   1st Qu.: 0.00    1st Qu.: 5.19   1st Qu.:0.00000   1st Qu.:0.4490 
## 
##  Median : 0.25651   Median : 0.00    Median : 9.69   Median :0.00000   Median :0.5380 
## 
##   Mean : 3.61352     Mean : 11.36     Mean :11.14     Mean :0.06917     Mean :0.5547  
## 
##  3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10   3rd Qu.:0.00000   3rd Qu.:0.6240 
## 
##  Max.  :88.97620    Max.  :100.00    Max.  :27.74    Max.  :1.00000    Max.  :0.8710  
## --------------------------------------------------------------------------------------
## 
## Table: Summary of Boston data (continued below)
## 
##  
## --------------------------------------------------------------------------------------------------
##       rm              age              dis              rad              tax           ptratio    
## --------------- ---------------- ---------------- ---------------- --------------- ---------------
##  Min.  :3.561     Min.  : 2.90    Min.  : 1.130    Min.  : 1.000    Min.  :187.0    Min.  :12.60  
## 
##  1st Qu.:5.886   1st Qu.: 45.02   1st Qu.: 2.100   1st Qu.: 4.000   1st Qu.:279.0   1st Qu.:17.40 
## 
##  Median :6.208   Median : 77.50   Median : 3.207   Median : 5.000   Median :330.0   Median :19.05 
## 
##   Mean :6.285     Mean : 68.57     Mean : 3.795     Mean : 9.549     Mean :408.2     Mean :18.46  
## 
##  3rd Qu.:6.623   3rd Qu.: 94.08   3rd Qu.: 5.188   3rd Qu.:24.000   3rd Qu.:666.0   3rd Qu.:20.20 
## 
##  Max.  :8.780    Max.  :100.00    Max.  :12.127    Max.  :24.000    Max.  :711.0    Max.  :22.00  
## --------------------------------------------------------------------------------------------------
## 
## Table: Table continues below
## 
##  
## ------------------------------------------------
##      black            lstat           medv      
## ---------------- --------------- ---------------
##   Min.  : 0.32    Min.  : 1.73    Min.  : 5.00  
## 
##  1st Qu.:375.38   1st Qu.: 6.95   1st Qu.:17.02 
## 
##  Median :391.44   Median :11.36   Median :21.20 
## 
##   Mean :356.67     Mean :12.65     Mean :22.53  
## 
##  3rd Qu.:396.23   3rd Qu.:16.95   3rd Qu.:25.00 
## 
##  Max.  :396.90    Max.  :37.97    Max.  :50.00  
## ------------------------------------------------</code></pre>
<p>After getting a statistical summary of, it’s worthwhile to see to what extent each variables are correlated. For that, we use <strong>corr()</strong> function on Boston data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corr_boston&lt;-<span class="kw">cor</span>(Boston) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">round</span>(<span class="dv">2</span>)
<span class="kw">pandoc.table</span>(corr_boston, <span class="dt">split.table =</span> <span class="dv">100</span>)</code></pre></div>
<pre><code>## 
## ---------------------------------------------------------------------------------------------
##    &amp;nbsp;      crim     zn     indus   chas     nox     rm      age     dis     rad     tax  
## ------------- ------- ------- ------- ------- ------- ------- ------- ------- ------- -------
##   **crim**       1     -0.2    0.41    -0.06   0.42    -0.22   0.35    -0.38   0.63    0.58  
## 
##    **zn**      -0.2      1     -0.53   -0.04   -0.52   0.31    -0.57   0.66    -0.31   -0.31 
## 
##   **indus**    0.41    -0.53     1     0.06    0.76    -0.39   0.64    -0.71    0.6    0.72  
## 
##   **chas**     -0.06   -0.04   0.06      1     0.09    0.09    0.09    -0.1    -0.01   -0.04 
## 
##    **nox**     0.42    -0.52   0.76    0.09      1     -0.3    0.73    -0.77   0.61    0.67  
## 
##    **rm**      -0.22   0.31    -0.39   0.09    -0.3      1     -0.24   0.21    -0.21   -0.29 
## 
##    **age**     0.35    -0.57   0.64    0.09    0.73    -0.24     1     -0.75   0.46    0.51  
## 
##    **dis**     -0.38   0.66    -0.71   -0.1    -0.77   0.21    -0.75     1     -0.49   -0.53 
## 
##    **rad**     0.63    -0.31    0.6    -0.01   0.61    -0.21   0.46    -0.49     1     0.91  
## 
##    **tax**     0.58    -0.31   0.72    -0.04   0.67    -0.29   0.51    -0.53   0.91      1   
## 
##  **ptratio**   0.29    -0.39   0.38    -0.12   0.19    -0.36   0.26    -0.23   0.46    0.46  
## 
##   **black**    -0.39   0.18    -0.36   0.05    -0.38   0.13    -0.27   0.29    -0.44   -0.44 
## 
##   **lstat**    0.46    -0.41    0.6    -0.05   0.59    -0.61    0.6    -0.5    0.49    0.54  
## 
##   **medv**     -0.39   0.36    -0.48   0.18    -0.43    0.7    -0.38   0.25    -0.38   -0.47 
## ---------------------------------------------------------------------------------------------
## 
## Table: Table continues below
## 
##  
## -----------------------------------------------
##    &amp;nbsp;      ptratio   black   lstat   medv  
## ------------- --------- ------- ------- -------
##   **crim**      0.29     -0.39   0.46    -0.39 
## 
##    **zn**       -0.39    0.18    -0.41   0.36  
## 
##   **indus**     0.38     -0.36    0.6    -0.48 
## 
##   **chas**      -0.12    0.05    -0.05   0.18  
## 
##    **nox**      0.19     -0.38   0.59    -0.43 
## 
##    **rm**       -0.36    0.13    -0.61    0.7  
## 
##    **age**      0.26     -0.27    0.6    -0.38 
## 
##    **dis**      -0.23    0.29    -0.5    0.25  
## 
##    **rad**      0.46     -0.44   0.49    -0.38 
## 
##    **tax**      0.46     -0.44   0.54    -0.47 
## 
##  **ptratio**      1      -0.18   0.37    -0.51 
## 
##   **black**     -0.18      1     -0.37   0.33  
## 
##   **lstat**     0.37     -0.37     1     -0.74 
## 
##   **medv**      -0.51    0.33    -0.74     1   
## -----------------------------------------------</code></pre>
<p>The table above shows the correlation matrix of all variables. Bird’s eye view on the matrix shows that <strong>tax</strong> (full-value property-tax rate) and <strong>rad</strong> (index of accessibility to radial highways) are the most positively correlated variables, whereas <strong>dis</strong> (weighted mean of distances to five Boston employment centres) and <strong>age</strong> (proportion of owner-occupied units built prior to 1940) are the most negatively correlated variables. Moreover, <strong>chas</strong> (Charles river dummy variable) and <strong>rad</strong> are the two variables that are least correlated.</p>
</div>
<div id="graphical-data-exploration" class="section level2 tabset tabset-pills">
<h2>Graphical data exploration</h2>
<p>The same information can be presented as a graphical overview. This time we will make a correlogram, a graphical representation of coorelation matrix. We will visualize the summary of the data using box plot and histogram. The <em>corrplot()</em> function of <strong>corrplot</strong> package wll be used to visualize the correlation between all the variables of the Boston dataset.</p>
<div id="correlation-plot" class="section level3">
<h3>Correlation plot</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">corrplot</span>(corr_boston, <span class="dt">method =</span> <span class="st">&quot;circle&quot;</span>, <span class="dt">tl.col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">cl.pos=</span><span class="st">&quot;b&quot;</span>, <span class="dt">tl.pos =</span> <span class="st">&quot;d&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;upper&quot;</span> , <span class="dt">tl.cex =</span> <span class="fl">0.9</span> )</code></pre></div>
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" width="864" /></p>
</div>
<div id="correlation-matrix" class="section level3">
<h3>Correlation matrix</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggpairs</span>(Boston)</code></pre></div>
<p><img src="index_files/figure-html/ggpairs-1.png" width="960" /></p>
<p>The above graphs gives much quicker impression regarding the variables. In the correlation graph, for example, positive correlations are displayed in blue and negative correlations in red color with intensity of the color and circle size being proportional to the correlation coefficients. The same relationship as described above using correlation summary can be seen in the form of circles with different size (intensity of correlation i.e highly correlated or lowly correlated) and different colors (wheether positively or negatively correlated).</p>
</div>
</div>
</div>
<div id="data-analysis" class="section level1">
<h1>Data Analysis</h1>
<p>After getting an overview of the data, we will employ multiple linear regression model (method) on the subset of the data to check how four variables (rad, medv, dis and black) are affecting crim.</p>
<div id="multiple-linear-regression" class="section level3">
<h3>Multiple Linear Regression</h3>
<p>Multiple linear regression is commonly used method for most of the the regression analyses. As a predictive analysis method, multiple linear regression describes given data and explain the relationship between one dependent variable and two or more independent variables. Our research question for the multiple linear regression is as follows: Can we explain the crime rate in Boston area based on the four variables that were hypothesized earlier in this report?</p>
<p>First, we need to check whether there is a linear relationship between the independent variables and the dependent variable in our multiple linear regression model. After that, we fit the model simply using <em>lm()</em> function and call output usig <em>summary()</em> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#let&#39;s first create subset of Boston data (my_Bos) using five variables kept in (my_var)</span>
myvar&lt;-<span class="kw">c</span>(<span class="st">&quot;crim&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;medv&quot;</span>, <span class="st">&quot;dis&quot;</span>, <span class="st">&quot;rad&quot;</span>)
my_Bos&lt;-<span class="kw">select</span>(Boston, <span class="kw">one_of</span>(myvar))
<span class="kw">ggpairs</span>(my_Bos)</code></pre></div>
<p><img src="index_files/figure-html/plot_myar-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#fit linear model</span>
lm_crim&lt;-<span class="kw">lm</span>(crim<span class="op">~</span>. , <span class="dt">data=</span>my_Bos)
<span class="co">#summarize the model</span>
<span class="kw">summary</span>(lm_crim)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = crim ~ ., data = my_Bos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.816  -1.668  -0.468   0.738  76.323 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  6.529163   1.730608   3.773 0.000181 ***
## black       -0.009053   0.003633  -2.492 0.013021 *  
## medv        -0.141722   0.034902  -4.061 5.68e-05 ***
## dis         -0.292778   0.159593  -1.835 0.067168 .  
## rad          0.483580   0.042263  11.442  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.524 on 501 degrees of freedom
## Multiple R-squared:  0.4293, Adjusted R-squared:  0.4247 
## F-statistic:  94.2 on 4 and 501 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>From the output, residuals represent the difference between the actual values i.e the crime rate in Boston and each of the four dependent variables. The next section shows the coefficients of the model. From the output, we saw that the intercept is 6.529163 with coefficients for dependant variables being -0.009053(black), -0.141722(medv), -0.292778(dis) and 0.483580(rad). Next, we can also see Standard errors for the coefficients which measure the average amount that the coefficient estimates differ from the dependent variables. Moreover, the t-value measures how far the coefficient estimation is away from zero with the assumption that the farther the better. In other words, we reject the null hypothesis when it’s far from zero.</p>
<p>In the above model, the t-values are farthest in <em>rad</em> followed by <em>medv</em>, <em>black</em> and <em>dis</em>. These values are also larger compared to standard error except <em>dis</em>, which indiciate that these variables do have some relationship with the <em>crime</em>. The last column indicates the probability for getting any value &gt;= <em>t</em>. In general, a p-value of 0.05 is good cut-off for significance. Thus, we can see that three (<em>black</em>, <em>medv</em> and <em>rad</em>) out of four choosen variables were significant.</p>
<p>The residual standard error indicates the quality of the regression model. This value some how gives how much we can be confident of our model. Here, the residual error is based on 501 degrees of freedom, where the degrees of freedom are data points used for estimating the parameters.</p>
<p>Finally, I would like to highlight to what extent my assumptions have been addressed by the model. Although I hypothesized that all of my four chosen variables have impact on crime, it turned out that the distance to employment centers (<em>dis</em>) is not significant variable to predict crime rate. Besides that, all three variables were significant with <em>rad</em> being the most significant one followed by <em>medv</em> and <em>black</em>.</p>
</div>
<div id="model-validation" class="section level3 tabset tabset-pills">
<h3>Model validation</h3>
<div id="residual-vs-fitted" class="section level4">
<h4>Residual vs Fitted</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(lm_crim, <span class="dt">which =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="index_files/figure-html/plot1-1.png" width="672" /></p>
</div>
<div id="normal-q-q" class="section level4">
<h4>Normal Q-Q</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(lm_crim, <span class="dt">which =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="index_files/figure-html/plot2-1.png" width="672" /></p>
</div>
<div id="residual-vs-leverage" class="section level4">
<h4>Residual vs Leverage</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(lm_crim, <span class="dt">which =</span> <span class="dv">5</span>)</code></pre></div>
<p><img src="index_files/figure-html/plot3-1.png" width="672" /></p>
</div>
</div>
<div id="interpretation-model-validation" class="section level3">
<h3>Interpretation (model validation)</h3>
<p>The three different diagnostic plots are generated above.The assumptions behind all three models is linearity and normality. Based on the above plots, we can conclude that the errors are normally distributed (clearly observed in q-q plot). Similarly, residual versus fitted model showed that the errors are not dependent on the crime variable. Moreover, we can see that few outliers (381, 406 and 410) have influences to the assumption that is clearly represented in case of residual vs leverage model and can be seen in other two plots as well. All the models have adressed the outliers nicely. Thus, assumptions in all models are more or less valid.</p>
</div>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>To conclude, three of the four variables I selected by assuming that they predict crime rate in Boston were found to be valid. Moreover, it was found that the median values of owner occupied homes turned out to be the best predictor among other variables.</p>
<div id="session-information" class="section level2">
<h2>Session information:</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sessionInfo</span>()</code></pre></div>
<pre><code>## R version 3.4.2 (2017-09-28)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 17.10
## 
## Matrix products: default
## BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=fi_FI.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=fi_FI.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=fi_FI.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=fi_FI.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] GGally_1.3.2  ggplot2_2.2.1 dplyr_0.7.4   corrplot_0.84 pander_0.6.1 
## [6] MASS_7.3-47  
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.12       knitr_1.16         bindr_0.1         
##  [4] magrittr_1.5       munsell_0.4.3      colorspace_1.3-2  
##  [7] R6_2.2.2           rlang_0.1.4        plyr_1.8.4        
## [10] stringr_1.2.0      tools_3.4.2        grid_3.4.2        
## [13] gtable_0.2.0       htmltools_0.3.6    lazyeval_0.2.0    
## [16] yaml_2.1.14        rprojroot_1.2      digest_0.6.12     
## [19] assertthat_0.2.0   tibble_1.3.4       bindrcpp_0.2      
## [22] reshape2_1.4.2     RColorBrewer_1.1-2 glue_1.2.0        
## [25] evaluate_0.10.1    rmarkdown_1.8      labeling_0.3      
## [28] stringi_1.1.5      compiler_3.4.2     scales_0.4.1      
## [31] backports_1.1.0    reshape_0.8.7      pkgconfig_2.0.1</code></pre>
<p><a href="http://www.twitter.com/kisunpokharel"><img src="http://i.imgur.com/tXSoThF.png" title="Twitter" alt="alt text" /></a> <a href="http://www.facebook.com/pokharel.kisun"><img src="http://i.imgur.com/P3YfQoD.png" title="Facebook" alt="alt text" /></a> <a href="http://www.github.com/kisun"><img src="http://i.imgur.com/0o48UoR.png" title="Github" alt="alt text" /></a></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
